"""Route and segment database models with PostGIS spatial geometries."""

from datetime import datetime
from typing import List, Optional
import uuid

from geoalchemy2 import Geometry
from sqlalchemy import (
    CheckConstraint,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from backend.app.core.database import Base
from backend.app.models.base import GUID, TimestampMixin, utc_now


class SavedRoute(Base, TimestampMixin):
    """User-saved or analyzed highway corridor route with PostGIS LineString geometry."""

    __tablename__ = "saved_routes"
    __table_args__ = (
        CheckConstraint("risk_score >= 0.0 AND risk_score <= 100.0", name="chk_saved_route_risk_score"),
        CheckConstraint("origin_lat >= -90.0 AND origin_lat <= 90.0", name="chk_saved_route_orig_lat"),
        CheckConstraint("origin_lon >= -180.0 AND origin_lon <= 180.0", name="chk_saved_route_orig_lon"),
        CheckConstraint("destination_lat >= -90.0 AND destination_lat <= 90.0", name="chk_saved_route_dest_lat"),
        CheckConstraint("destination_lon >= -180.0 AND destination_lon <= 180.0", name="chk_saved_route_dest_lon"),
        Index("idx_saved_routes_user_id", "user_id"),
        Index("idx_saved_routes_risk_tier", "risk_tier"),
        Index("idx_saved_routes_created_at", "created_at"),
    )

    id: Mapped[uuid.UUID] = mapped_column(GUID(), primary_key=True, default=uuid.uuid4)
    user_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        GUID(),
        ForeignKey("user_profiles.id", ondelete="SET NULL"),
        nullable=True,
    )
    name: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    origin_name: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    destination_name: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    origin_lat: Mapped[float] = mapped_column(Float, nullable=False)
    origin_lon: Mapped[float] = mapped_column(Float, nullable=False)
    destination_lat: Mapped[float] = mapped_column(Float, nullable=False)
    destination_lon: Mapped[float] = mapped_column(Float, nullable=False)

    vehicle_profile: Mapped[str] = mapped_column(String(50), default="driving-car", nullable=False)
    provider: Mapped[str] = mapped_column(String(50), default="OSRM", nullable=False)

    distance_km: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    risk_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    risk_tier: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)
    analysis_status: Mapped[Optional[str]] = mapped_column(String(20), default="COMPLETE", nullable=True)

    # PostGIS 2D LineString in WGS84 Geographic CRS (EPSG:4326)
    route_geometry = mapped_column(
        Geometry(geometry_type="LINESTRING", srid=4326, spatial_index=True),
        nullable=True,
    )

    # Relationships
    user = relationship("UserProfile", back_populates="saved_routes")
    segments = relationship(
        "RouteSegment",
        back_populates="route",
        cascade="all, delete-orphan",
        order_by="RouteSegment.segment_index",
    )
    risk_assessments = relationship(
        "RiskAssessment",
        back_populates="route",
        cascade="all, delete-orphan",
    )
    feedback = relationship("Feedback", back_populates="route")
    monitored_trips = relationship(
        "MonitoredTrip",
        back_populates="route",
        cascade="all, delete-orphan",
    )

    def __repr__(self) -> str:
        return f"<SavedRoute id={self.id} {self.origin_name}->{self.destination_name} risk={self.risk_score}>"


class RouteSegment(Base):
    """Uniform 250m discrete road segment generated by the analytical segmenter."""

    __tablename__ = "route_segments"
    __table_args__ = (
        CheckConstraint("risk_score >= 0.0 AND risk_score <= 100.0", name="chk_segment_risk_score"),
        CheckConstraint("length_m > 0.0", name="chk_segment_length_positive"),
        Index("idx_route_segments_route_id", "route_id"),
        Index("idx_route_segments_risk_tier", "risk_tier"),
        Index("idx_route_segments_segment_id", "segment_id"),
    )

    id: Mapped[uuid.UUID] = mapped_column(GUID(), primary_key=True, default=uuid.uuid4)
    route_id: Mapped[uuid.UUID] = mapped_column(
        GUID(),
        ForeignKey("saved_routes.id", ondelete="CASCADE"),
        nullable=False,
    )
    segment_index: Mapped[int] = mapped_column(Integer, nullable=False)
    segment_id: Mapped[str] = mapped_column(String(100), nullable=False)

    start_chainage_m: Mapped[float] = mapped_column(Float, nullable=False)
    end_chainage_m: Mapped[float] = mapped_column(Float, nullable=False)
    length_m: Mapped[float] = mapped_column(Float, default=250.0, nullable=False)
    bearing_deg: Mapped[Optional[float]] = mapped_column(Float, nullable=True)

    # PostGIS Point and LineString geometries in WGS84 (EPSG:4326)
    midpoint = mapped_column(
        Geometry(geometry_type="POINT", srid=4326, spatial_index=True),
        nullable=True,
    )
    geometry = mapped_column(
        Geometry(geometry_type="LINESTRING", srid=4326, spatial_index=True),
        nullable=True,
    )

    risk_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    risk_tier: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)
    analysis_status: Mapped[Optional[str]] = mapped_column(String(20), default="COMPLETE", nullable=True)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utc_now, nullable=False)

    # Relationships
    route = relationship("SavedRoute", back_populates="segments")
    risk_assessments = relationship(
        "RiskAssessment",
        back_populates="segment",
        cascade="all, delete-orphan",
    )
    risk_snapshots = relationship(
        "TripRiskSnapshot",
        back_populates="segment",
        cascade="all, delete-orphan",
    )
    trip_alerts = relationship(
        "TripAlert",
        back_populates="affected_segment",
        cascade="all, delete-orphan",
    )

    def __repr__(self) -> str:
        return f"<RouteSegment id={self.id} route_id={self.route_id} idx={self.segment_index} risk={self.risk_score}>"
